// Editorial source material. These original worlds are fiction, not licensed franchises.
export const worlds = [
  {
    category: 'Anime', slug: 'anime', fandom: 'Lumen Crossing', colors: ['#f5a9ce', '#8c48c7', '#20132f'], motif: 'moon',
    articles: [
      ['The quiet frame: finding emotion between the action', 'A held glance, an empty platform and a passing cloud can tell a story before anyone speaks.', 'Start with the pause', 'Watch a scene once for the plot, then again for the spaces between lines. A stationary shot gives the eye time to notice a hand tightening around a bag or a character standing apart from a group. Those small choices can communicate hesitation without a speech.', 'Build a viewing notebook', 'Record one image rather than a full episode summary. Describe its colors, the distance between people and what changed immediately afterward. Compare a busy action sequence with a quiet transition: the contrast is often what gives both moments their weight. Keep your notes spoiler-free by describing the technique rather than the outcome.'],
      ['Three colors, one mood: a sunset palette study', 'Explore how amber, violet and midnight blue turn an ordinary rooftop into a place of possibility.', 'Choose an emotional direction', 'A limited palette helps a setting feel coherent. Try warm light against a cool skyline, then reserve the brightest tone for the object the audience should notice first. The colors do not have fixed meanings; their relationships matter more than a universal color rule.', 'Make the exercise your own', 'Sketch the same rooftop at noon and at dusk. Keep the buildings in place while changing the light and shadow. Ask which version feels more private and explain why. This exercise uses an original imaginary city, so there is no need to copy a frame from a commercial series.'],
    ],
    character: ['Aiko Ren — the rooftop astronomer', 'A patient sky-mapper who must learn that asking for help is not the opposite of being brave.', 'Aiko maintains the abandoned observatory above Lumen Crossing. Her brass telescope can locate missing stars, but only when someone nearby tells the truth. She carries a notebook of unfinished maps and repairs lenses with parts salvaged from old cameras.', 'When her closest friend vanishes from every constellation chart, Aiko has to leave the rooftop and follow the city beneath it. Her strength is attention; her flaw is treating people like puzzles that can be solved alone. Her story turns on choosing a conversation over a perfect calculation.', 'telescope'],
    gallery: ['Lumen Crossing after sunset', 'A three-scene original art study of moonlit rooftops, lantern paths and the observatory horizon.', ['Rooftop silhouettes', 'The lantern path', 'An open sky']],
    audio: ['Aiko’s first observation', 'An original fictional field note about the first light above the city.', 'Tonight the observatory is quiet. I can hear the wind turning the loose sign below the stairs. There is one light where my map says the sky should be empty. I almost erased it. Then I remembered that a map is a question, not an answer. Tomorrow I will ask someone to climb the hill with me. Some discoveries are too large to carry alone.'],
    video: ['From twilight to starlight', 'A narrated motion study of the color, silhouette and focal point in an original anime-inspired setting.', 'Begin with the horizon. A low skyline leaves room for the sky to carry the mood. Next, separate warm lantern light from cool distant buildings. Give one small point of light more contrast than everything around it. Finally, hold the composition long enough for the viewer to discover that point. This is a visual planning exercise for Lumen Crossing, an original fictional world.'],
    product: ['Observatory field journal', 'A midnight-blue notebook concept with a constellation cover and a brass-colored corner detail.', 'The design pairs a dark cover with a single orbital mark. Inside, alternating plain and dotted pages would support sketches, viewing notes and star maps. A narrow ribbon marker follows the warm accent used in Aiko’s telescope. This is an original product-design concept for the showcase; no stock or purchase is offered.', 'book'],
  },
  {
    category: 'Gaming', slug: 'gaming', fandom: 'Relay Frontier', colors: ['#80f4ca', '#198ca1', '#092934'], motif: 'controller',
    articles: [
      ['Co-op without the chaos: design a better first session', 'Give every player a useful role, a clear objective and permission to learn at their own pace.', 'Agree on a small goal', 'A first session works best when success is easy to describe. Choose one mission, one puzzle room or a short shared challenge. Let players check controls and accessibility settings before the timer starts. Ask whether the group wants hints rather than assuming that everyone enjoys the same level of pressure.', 'Rotate the responsibility', 'Trade navigation, resource tracking and decision-making between rounds. A quieter player may contribute more when the task has a defined shape. End with one moment each person enjoyed and one change for next time. A welcoming session creates a reason to return even when the team does not win.'],
      ['Readable worlds: how a path invites exploration', 'Landmarks, contrast and repeated shapes can guide a player without covering the screen in arrows.', 'Give the eye an anchor', 'A tower, a bright doorway or a moving light can become a reference point. Place it where the player can rediscover it after a detour. A useful landmark differs from its surroundings in more than one way: shape and brightness often work better together than color alone.', 'Reward curiosity', 'A side route should offer a different view, a small story or a useful connection back to the main path. Sketch a level with three spaces and one visible destination. Test the sketch with someone who has not seen it before. Their hesitation tells you more than your explanation of where they should have gone.'],
    ],
    character: ['Nox Vale — the relay engineer', 'A resourceful station mechanic whose greatest tool is the trust of a scattered crew.', 'Nox repairs communication relays on the edge of an uncharted asteroid belt. A modular gauntlet turns scrap into temporary bridges and signal beacons. His companion is a small maintenance drone named Pip, whose damaged memory contains fragments of a missing expedition.', 'Nox can improvise almost anything except an apology. When a shortcut strands his crew on separate stations, the mission becomes a sequence of promises he must keep. He wins by reconnecting people rather than collecting a more powerful weapon.', 'robot'],
    gallery: ['Wayfinding on the frontier', 'Three original environment diagrams explore a beacon, an orbital route and a landing grid.', ['The central beacon', 'Orbit and return', 'Landing coordinates']],
    audio: ['Pip, are you receiving?', 'A short fictional relay transmission from a mechanic trying to reconnect his crew.', 'Relay three is online. Pip, if you can hear this, blink twice. There you are. I took the shorter route and I was wrong. The crew is waiting for a signal, not an excuse. We have one battery, a damaged antenna and enough cable for a second attempt. Let us make the connection before we start counting the things we do not have.'],
    video: ['A level in three landmarks', 'An original narrated layout study follows a beacon, a route and a destination.', 'A readable route begins with a destination the player can recognize. Put the beacon above the surrounding shapes. Use a repeated line to connect the foreground with the next platform. Leave one optional path that returns to the main route. At the landing zone, repeat the beacon color so arrival feels intentional. These diagrams describe a fictional level, not footage from a released game.'],
    product: ['Relay desk mat', 'A teal navigation-grid desk mat concept with a clear central play area.', 'The proposed mat uses a quiet grid instead of a dense collage. Coordinates sit near the edge, leaving the center open for a keyboard or controller. A bright relay emblem marks one corner and a darker border frames the surface. It is a visual concept, without a manufactured material specification or checkout.', 'mat'],
  },
  {
    category: 'Movies', slug: 'movies', fandom: 'The Last Lighthouse', colors: ['#ffd199', '#be6942', '#291824'], motif: 'film',
    articles: [
      ['One lamp, three stories', 'Move a single light around a subject and watch the same room change its emotional temperature.', 'Look at direction first', 'Front light reveals a face clearly; side light creates a stronger boundary between light and shadow. Back light separates a figure from the room. None of these choices guarantees a particular emotion, but each changes the information available to the audience.', 'Compare before adding more', 'Use a safe household lamp and an ordinary object. Photograph it from the same position with the light in three places. Keep a note of the shadow edge and the background. A simple exercise makes it easier to recognize deliberate lighting when you return to a favorite film.'],
      ['The object that tells the story', 'A key, a letter or a chipped cup can carry history without a long explanation.', 'Introduce the ordinary version', 'Let the audience see an object doing its everyday job before giving it special significance. A cup on a breakfast table becomes more interesting when the same cup later sits untouched in an empty room. Repetition gives the viewer something concrete to compare.', 'Change the context', 'Write a short scene in which a character passes an object to someone else without dialogue. Decide what the handover costs them. Keep the prop simple and the action specific. The emotional detail comes from the relationship around the object, not from making the object mysterious.'],
    ],
    character: ['Mara Flint — keeper of the last light', 'A practical lighthouse keeper facing a storm and a message she has avoided for years.', 'Mara lives on a small island with a failing lamp and a box of letters from the mainland. She knows every stair in the tower and every warning in the sound of the sea. Her yellow coat, oil-stained gloves and carefully repaired lantern tell the story of someone who keeps things working.', 'The arrival of an unfamiliar boat forces her to choose between guarding the place she knows and answering the person she left behind. Mara’s fictional film story is about responsibility, grief and the courage to let another person share the watch.', 'lantern'],
    gallery: ['Light, shadow and the sea', 'An original set of cinematic composition boards for a coastal story.', ['The light above the harbor', 'A window in the storm', 'The long way home']],
    audio: ['The midnight watch', 'Mara’s fictional lighthouse log, read as a quiet spoken vignette.', 'The lamp held through midnight. There is salt on the inside of the window again, and the west stair needs another nail. A boat crossed the outer light just before the rain. I kept telling myself it was a fishing crew. Then I saw the blue flag. I have carried that letter for six years. In the morning, I will finally open it.'],
    video: ['Lighting the last lighthouse', 'A short narrated visual essay about contrast and focal light in a coastal composition.', 'Start with a dark horizon and one warm source. The lamp gives the viewer a place to look before the tower becomes visible. Add a reflected path to connect that light with the foreground. In the second composition, the window becomes the focal point. In the final view, reduce the contrast to make the same place feel calmer. These are original composition boards rather than film excerpts.'],
    product: ['Keeper’s lantern print', 'A warm-toned art-print concept built around the lighthouse’s guiding beam.', 'A tall lantern silhouette occupies the center of the print while fine concentric lines suggest light reaching the sea. The design uses amber, charcoal and a small cream highlight. It is intended as a display-only print concept, with no claim of an official film collaboration.', 'print'],
  },
  {
    category: 'TV Shows', slug: 'tv', fandom: 'Archive Nine', colors: ['#a6c7ff', '#586cd4', '#121e3a'], motif: 'screen',
    articles: [
      ['A watch club that leaves room for everyone', 'Make discussion welcoming with a clear spoiler boundary and questions that invite different readings.', 'Set the boundary before pressing play', 'Agree on the last episode everyone has finished. Put later plot details in a separate conversation. Give people a way to pass on a question and avoid turning a discussion into a test of who remembers the most names.', 'Ask about choices', 'Instead of asking for the correct interpretation, ask which decision surprised someone and what detail shaped their view. Save predictions separately from confirmed events. Finish by choosing the next viewing checkpoint together. A good watch club makes people more curious, not more anxious about missing something.'],
      ['The season notebook: tracking a long story', 'Keep characters, recurring objects and unanswered questions organized without rewriting every episode.', 'Separate facts from predictions', 'Use one column for what the episode actually shows and another for your interpretation. This prevents a clever theory from quietly becoming a remembered fact. Keep each note short enough to scan before the next viewing session.', 'Follow a thread', 'Choose one recurring detail, such as a place or an object, and record when its meaning changes. At the end of the season, reread only that thread. You may notice how a background detail became central or how a confident prediction changed as new information arrived.'],
    ],
    character: ['Mira Sol — archivist of the missing hour', 'A records specialist who discovers that every clock in the city has forgotten the same sixty minutes.', 'Mira catalogs damaged recordings beneath the central railway station. She notices mismatched timestamps that everyone else dismisses as equipment faults. Her portable recorder captures a voice that can only be heard between the final train and the first announcement of the morning.', 'Mira trusts documents more readily than people. Her investigation becomes a fictional serial mystery about whose memories are preserved and whose are left out. The blue scarf around her recorder belonged to the first person who believed her account.', 'recorder'],
    gallery: ['Inside Archive Nine', 'Original scene boards move from an empty control room to a corridor of unfinished records.', ['The empty control room', 'Cabinet of echoes', 'The missing hour']],
    audio: ['Tape zero: do not rewind', 'An original mystery monologue from the archive beneath the station.', 'If you are hearing this, the clocks have started again. Do not rewind the tape yet. Write down the first thing you remember about this morning. Mine was the sound of a train, but there was no train on the schedule. Someone has filed the missing hour under maintenance. I think they expected us to stop asking once the lights came back on.'],
    video: ['Building a mystery through objects', 'A narrated sequence studies the screen, the record and the repeated clock motif.', 'A mystery does not need to reveal its answer in the opening image. Begin with an ordinary room and one detail that does not belong. Repeat that detail in a second place. Let the audience compare the two before introducing a third clue. In Archive Nine, circles suggest clocks while parallel lines suggest stored records. The visual pattern connects the scenes without explaining the missing hour.'],
    product: ['Archive Nine messenger bag', 'A compact navy bag concept with a recorder pocket and an archival label panel.', 'The front flap carries a numbered label and a single blue line inspired by recording tape. The illustrated pocket is sized as a visual feature, not a verified manufacturing measurement. This original accessory concept accompanies Mira’s story and is displayed without a purchase option.', 'bag'],
  },
  {
    category: 'K-Pop', slug: 'kpop', fandom: 'Prism Avenue', colors: ['#ffb3e2', '#c54596', '#321530'], motif: 'headphones',
    articles: [
      ['Listen beyond the chorus', 'Use a listening journal to notice arrangement, texture and the small changes that reward a replay.', 'Choose one layer at a time', 'On the first listen, follow the main melody. On the next, pay attention to percussion or the space around the vocal. Write concrete observations such as a new harmony entering or the rhythm becoming sparse rather than judging every moment immediately.', 'Keep the entry personal', 'Record the setting in which you listened and a single detail you want to hear again. Your journal is not a ranking system. Leave room for a track to grow on you, and separate your reaction from claims about an artist’s intention.'],
      ['A fan zine with a clear visual rhythm', 'Plan a small editorial spread around a palette, a grid and enough breathing room for the words.', 'Build a hierarchy', 'Choose one headline size, one body size and a small label style. Make the reading order obvious before adding decoration. A restrained palette helps photographs and illustrations feel related without forcing every page to look identical.', 'Credit what you use', 'Use your own writing and artwork or material you have permission to include. Keep a source list while assembling the zine. Print a rough page or view it at its intended size: text that looked elegant while zoomed in may be hard to read at normal scale.'],
    ],
    character: ['Yuna Park — the sound collector', 'An original fictional producer who finds rhythm in the city before she finds it in a studio.', 'Yuna carries a small recorder and a notebook full of sounds: a station gate, rain on an awning, the click of a bicycle stand. In the fictional Prism Avenue collective, she turns these fragments into arrangements while learning how to share unfinished work.', 'Her perfectionism makes collaboration difficult. The first track she allows someone else to change becomes the one that finally sounds like a group. Yuna is an invented character, not a portrayal of a real performer or an imitation of an artist’s voice.', 'headphones'],
    gallery: ['Prism Avenue color sessions', 'Original graphic studies explore a stage glow, a listening room and a magenta rhythm grid.', ['Stage glow', 'The listening room', 'Rhythm in color']],
    audio: ['Before the first take', 'An original spoken studio note about listening, mistakes and collaboration.', 'Before we record, listen to the room. There is a little hum near the window and a chair that clicks when someone leans back. We could remove every trace of being here, but I want to keep one. Not the mistake that distracts from the song. The small sound that reminds us we made it together. Ready? Let us start with the part nobody has heard yet.'],
    video: ['A visual rhythm in three frames', 'An original narrated design study connects repetition, contrast and a final accent.', 'A repeated shape creates a pulse for the eye. Keep the spacing regular, then change one element to make an accent. A second color can introduce a new layer without increasing the number of shapes. Finally, leave a quiet area so the composition has room to breathe. This motion study is about visual rhythm; it does not contain a commercial song or an artist performance.'],
    product: ['Prism listening notebook', 'A blush-and-magenta journal concept for track notes and personal listening reflections.', 'Rounded bars on the cover suggest a sound meter while a pale vertical strip holds a handwritten date. The imagined inside layout separates first impressions from details noticed on a replay. This is an original stationery concept, not an official artist product.', 'book'],
  },
  {
    category: 'Comics', slug: 'comics', fandom: 'Lantern District', colors: ['#ffe18a', '#d28a35', '#2e2330'], motif: 'panels',
    articles: [
      ['The space between panels', 'Explore how a reader supplies movement and time in the gap between two still images.', 'Choose the missing action', 'Draw a hand reaching for a door in one panel and the open doorway in the next. The reader completes the movement. A larger jump might move from an empty street to a crowded station, asking the reader to infer both travel and elapsed time.', 'Control the pace', 'Several small panels can slow down a short action by breaking it into beats. A wide panel can give a scene room to settle. Sketch a six-panel page twice with different panel sizes and compare how quickly you read it, even when the words remain unchanged.'],
      ['Lettering that leads the eye', 'Place speech balloons early so dialogue and artwork work together instead of competing.', 'Plan the reading route', 'Mark rough balloon positions before drawing detailed backgrounds. Keep the order easy to follow and leave a consistent space between words and the balloon edge. The tail should identify the speaker without crossing unrelated text.', 'Test at reading size', 'Reduce the page to the size at which someone will actually read it. Check whether lettering remains comfortable and whether a balloon hides an important expression. When a page feels crowded, shorten a sentence or move a beat rather than shrinking all the text.'],
    ],
    character: ['Sable Quill — the lantern cartographer', 'A courier who maps safe routes through a city whose streets rearrange after dark.', 'Sable carries a folding lantern that reveals yesterday’s streets beneath today’s buildings. Her coat is lined with unfinished maps, each marked by a person she has promised to bring home. She navigates by listening to the stories attached to corners and doorways.', 'She can remember every route except the one that led her brother away. Her original comic story asks whether a map should preserve a city exactly as it was or help its people build something new. Her signature tool is a blunt pencil that never quite reaches its last mark.', 'lantern'],
    gallery: ['Routes through the Lantern District', 'Three original panels study a glowing sign, a broken route and a city seen from above.', ['A sign in the rain', 'The interrupted route', 'A city of crossings']],
    audio: ['A route worth keeping', 'A fictional courier’s message about finding a way home through a changing city.', 'The street on your map is gone. Do not worry. Follow the bakery lights until you reach the painted door. Someone moved the bridge again, but the old woman on the corner remembers where it went. That is the thing about this city. The buildings keep changing their minds. The people keep leaving directions for one another. I will meet you at the last lantern.'],
    video: ['A page that moves without moving', 'A narrated panel-layout study shows how scale and spacing create a reading pace.', 'The first panel establishes a place. The second moves closer to the object that matters. The third allows a pause before the next action. Notice how a narrow panel changes the amount of information you can take in at once. The gutters keep each moment separate while inviting the reader to connect them. These original boards are a layout exercise for the Lantern District.'],
    product: ['Lantern route enamel-pin concept', 'A golden lantern emblem framed by a winding route and a dark outline.', 'The proposed pin reduces Sable’s map-making tools to one readable silhouette. A looping line suggests a route without reproducing a real street map. The image is an original concept illustration; enamel, size and attachment details have not been manufactured or tested.', 'pin'],
  },
  {
    category: 'Manga', slug: 'manga', fandom: 'Paper Harbor', colors: ['#e9ece5', '#819b9c', '#19282e'], motif: 'ink',
    articles: [
      ['Make black, white and space work together', 'Build a readable page by deciding where the darkest shapes belong before adding detail.', 'Start with large values', 'Reduce a sketch to three groups: light, middle and dark. A small dark figure against a light wall may be easier to read than a detailed figure surrounded by texture. Keep the focal area clear enough that the reader can find it at a glance.', 'Add texture with a purpose', 'Use hatching or a repeated tone to describe material and depth, then stop before the pattern competes with the action. Flip between a thumbnail view and a close view while drawing. The thumbnail reveals whether the page still works as a whole.'],
      ['A sketchbook of gestures, not perfect poses', 'Practice the direction and weight of a movement before worrying about every contour.', 'Find the main action', 'Begin with a line that describes the overall movement. Add a simple shape for the torso and mark the supporting foot. The aim is to understand balance, not to finish a polished character drawing in one attempt.', 'Review the sequence', 'Place several quick sketches beside one another and ask which has the clearest movement. Circle the useful attempt and write one observation. A page of experiments becomes valuable when it records what you learned, including the poses that did not work.'],
    ],
    character: ['Ren Ito — the paper-boat messenger', 'A quiet apprentice whose folded letters sail toward people who have forgotten how to reply.', 'Ren works in a bookbinding shop beside Paper Harbor. At closing time he folds discarded proofs into boats and sends them through the canals. Each boat carries an unfinished sentence that finds the person who needs to finish it.', 'He is good at carrying other people’s words and poor at saying his own. His fictional coming-of-age story begins when a boat returns with a blank page. Ren must decide what he wants to say before the tide can take it anywhere.', 'boat'],
    gallery: ['Paper Harbor in monochrome', 'Original ink-style compositions study folded paper, canal lines and the negative space around a bridge.', ['The first fold', 'Canal reflections', 'Under the paper bridge']],
    audio: ['A letter without an address', 'An original fictional reading from a messenger learning to write his own reply.', 'I folded the page three times before I noticed it was blank. Usually the words arrive first. A promise, an apology, a sentence someone could not finish. This time there was only the sound of the canal. So I wrote one line of my own. I would like to stay. The boat did not move until I stopped holding the string.'],
    video: ['Less ink, clearer story', 'A narrated composition exercise follows silhouette, white space and a final line accent.', 'Begin with the largest dark shape. Let the surrounding white space describe its edge. Add only the lines that explain a change of direction or material. In the second frame, notice how a repeated diagonal suggests a folded surface. In the last, leave an open area where the eye can rest. The exercise uses original drawings inspired by paper and water.'],
    product: ['Paper Harbor bookmark set', 'Three slim bookmark concepts featuring a folded boat, a canal line and an open page.', 'Each illustrated bookmark uses a different arrangement of black, cream and muted green. The narrow format keeps the motif simple and leaves room for a short handwritten note on the reverse. These are original paper-product concepts, shown without inventory or pricing.', 'bookmarks'],
  },
  {
    category: 'Cosplay', slug: 'cosplay', fandom: 'Aether Workshop', colors: ['#c5b5ff', '#8156c9', '#251b39'], motif: 'mask',
    articles: [
      ['From silhouette to costume plan', 'Break an ambitious character design into recognizable shapes and manageable build decisions.', 'Identify the signature shape', 'Look for the feature that makes the design readable from a distance: a collar, a cape, a shoulder line or a distinctive bag. Sketch the silhouette before listing small details. Choose a version you can comfortably wear, sit in and move around in.', 'Prototype before committing', 'Use paper or inexpensive fabric to test proportions. Keep a list of materials, attachment points and parts that need to come apart for transport. Follow the instructions for your tools and materials, and check the event’s costume and prop rules before planning a large accessory.'],
      ['The convention repair pouch', 'Prepare a small, practical kit around the actual weak points of your costume.', 'Inspect the build', 'Try the costume on and identify where straps, seams or fasteners are under strain. Pack compatible spare fasteners, a small sewing kit and any simple repair items permitted by the venue. Label detachable pieces so another person can help you reassemble them.', 'Plan for the day', 'Practice carrying the costume and keeping your hands free. Allow for water, breaks and changing conditions. A successful build is not just a photograph: it is something you can enjoy wearing for the time you have planned. Ask before photographing another attendee and respect their answer.'],
    ],
    character: ['Elara Voss — the skyship tailor', 'An inventive costume-world heroine who repairs sails and friendships with equal determination.', 'Elara runs a tiny workshop aboard a traveling skyship. Her violet coat has detachable sleeves, brass loops and pockets for folded patterns. She can read the stress in a torn sail the way other people read a letter.', 'When the captain commissions a ceremonial cape during a storm, Elara must choose between a beautiful display and the repairs that will keep the crew aloft. Her original story celebrates practical making and the confidence to tell someone what a design really needs.', 'scissors'],
    gallery: ['Aether Workshop material boards', 'Original illustrations compare a mask silhouette, layered fabric and the lines of a pattern.', ['The mask silhouette', 'Layered color', 'Pattern and proportion']],
    audio: ['Measure twice, leave room to move', 'A fictional maker’s note about the person who has to wear the finished costume.', 'The drawing never has to climb a staircase. You do. Before we add another buckle, raise your arms and turn around. Good. That is the shape we need to protect. We can make the collar dramatic without making it heavy. We can make the coat memorable without hiding the person inside it. A costume should give you room to become someone, not take your room away.'],
    video: ['A costume begins with a silhouette', 'An original narrated design board moves from the large shape to accents and practical details.', 'Start with a silhouette that reads from across the room. Divide it into a main shape, a supporting layer and one accent. Repeat a color in two small places to connect the design. Before adding detail, consider where the wearer bends and where the costume separates for transport. These original boards are design concepts, not a step-by-step construction or tool-safety tutorial.'],
    product: ['Aether detachable cape concept', 'A violet shoulder-cape concept with contrasting lining and simple geometric trim.', 'The design uses a short outer layer to keep the silhouette clear while suggesting freedom of movement. The illustrated collar and fasteners are conceptual and need practical testing before a real build. It belongs to the original Aether Workshop collection and is not a ready-to-buy garment.', 'cape'],
  },
];
